
export const localization = {
    "en-GB": {
        "home": "Home",
        "category": "Category",
        "mybag": "My Bag",
        "contact": "Contact Us",
        "mycheckout": "Checkout",
        "myaccount": "My Account",
        "viewaddress": "View Address",
        "editaddress": "Edit Address",
        "mywishlist": "My Wishlist",
        "subtotal": "Subtotal",
        "checkout": "Checkout",
        "viewbag": "View Bag",
        "phone": "Phone",
        "items": "Items",
        "searchyourproduct": "Search your product",
        "admin": "Admin",
        "dashboard": "Dashboard",
        "orders": "Orders",
        "download": "Download",
        "payment": "Payment",
        "address": "Address",
        "accountdetails": "Account Details",
        "allcategories": "All Categories",
        "product": "Product",
        "search": "Search",
        "browse": "Browse",
        "accessories": "Accessories",
        "fashion": "Fashion",
        "fruit": "Fruit",
        "vegetables": "Vegetables",
        "nuts": "Nuts",
        "homeandlifestyle": "Home & Lifestyle",
    },
    "zh-HK": {
        "home": "首頁",
        "category": "類別",
        "mybag": "購物車",
        "contact": "聯繫我們",
        "mycheckout": "付款",
        "myaccount": "我的帳戶",
        "mywishlist": "我的收藏",
        "subtotal": "訂單總額",
        "checkout": "付款",
        "viewbag": "查看包",
        "phone": "電話",
        "items": "項目",
        "searchyourproduct": "搜索你的產品",
        "allcategories": "所有類別",
        "product": "產品",
        "search": "搜索",
        "browse": "瀏覽",
        "accessories": "飾物",
        "fashion": "時裝",
        "homeandlifestyle": "家居",
        "fruit": "水果",
        "vegetables": "蔬菜",
        "nuts": "堅果",
    }
}